version: 2.1
jobs:
  test:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - run: pip install requests
      - run: python -m unittest -v test_classify_triangle.py
      - run: cd GitHubApi567-hw03a && python -m unittest -v test_github_repos.py
workflows:
  tests:
    jobs:
      - test
